config/routes.rb
Rails.application.routes.draw do
  resources :weapons
  resources :armor_shields
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :features
  resources :languages
  resources :races
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/race.rb
class Race < ApplicationRecord
  enum size: [:tiny, :small, :medium, :large, :huge, :gargantuan]

  has_many :language_speakers, as: :speaker, dependent: :destroy, inverse_of: :speaker
  has_many :languages, through: :language_speakers
  has_many :features, as: :owner, dependent: :destroy

  validates_presence_of :name, :description
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: %i[ show edit update destroy ]

  def index
    @races = Race.all
  end

  def show
  end

  def new
    @race = Race.new
  end

  def edit
  end

  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to race_url(@race), notice: "Race was successfully created." }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to race_url(@race), notice: "Race was successfully updated." }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url, notice: "Race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_race
    @race = Race.find(params[:id])
  end

  def race_params
    params.require(:race).permit(:name, :description, :size, :speed)
  end
end

app/helpers/races_helper.rb
module RacesHelper
end

app/views/races/_form.html.erb
<%= form_with(model: race) do |form| %>
  <% if race.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(race.errors.count, "error") %> prohibited this race from being saved:</h2>

      <ul>
        <% race.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.select :size, options_for_select(Race.sizes.map {|key, value| [key.titleize, Race.sizes.key(value)]}) %>
  </div>

  <div>
    <%= form.label :speed, style: "display: block" %>
    <%= form.number_field :speed %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/races/_race.html.erb
<div id="<%= dom_id race %>">
  <p>
    <strong>Name:</strong>
    <%= race.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= race.description %>
  </p>

  <p class="">
    <strong>Size:</strong>
    <%= race.size.titleize %>
  </p>

  <p>
    <strong>Speed:</strong>
    <%= race.speed %>m
  </p>

</div>

app/views/races/edit.html.erb
<h1>Editing race</h1>

<%= render "form", race: @race %>

<br>

<div>
  <%= link_to "Show this race", @race %> |
  <%= link_to "Back to races", races_path %>
</div>

app/views/races/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Races</h1>

<div id="races">
  <% @races.each do |race| %>
    <%= render race %>
    <p>
      <%= link_to "Show this race", race %>
    </p>
  <% end %>
</div>

<%= link_to "New race", new_race_path %>

app/views/races/new.html.erb
<h1>New race</h1>

<%= render "form", race: @race %>

<br>

<div>
  <%= link_to "Back to races", races_path %>
</div>

app/views/races/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @race %>

<div>
  <%= link_to "Edit this race", edit_race_path(@race) %> |
  <%= link_to "Back to races", races_path %>

  <%= button_to "Destroy this race", @race, method: :delete %>
</div>