config/routes.rb
Rails.application.routes.draw do
  resources :weapons
  resources :armor_shields
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :features
  resources :languages
  resources :races
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  belongs_to :damage_type, optional: true
  has_many :weapon_property_weapon, dependent: :destroy
  has_many :weapon_properties, through: :weapon_property_weapon

  enum weapon_type: [
    :simple_melee,
    :simple_ranged,
    :martial_melee,
    :martial_ranged,
    :ammunition,
  ]

  def cost=(cost)
    self.cost_cp = cost_conversion(cost)
  end

  def cost
    # It defaults to gold pieces, since it's standard

    "#{self.cost_cp.to_f / 100} gp"
  end

  def self.ransackable_associations(auth_object = nil)
    ["damage_type", "weapon_properties", "weapon_property_weapon"]
  end

  private

  COST_MAP = {
    'cp' => 1,
    'sp' => 10,
    'ep' => 50,
    'gp' => 100,
    'pp' => 1000,
  }

  def cost_conversion(cost)
    amount, unit = cost.split(' ')

    amount.to_i * COST_MAP[unit]
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < InheritedResources::Base

  private

    def weapon_params
      params.require(:weapon).permit(:name, :cost_cp, :weight, :damage_dice, :damage_type_id)
    end

end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/weapons/_form.html.erb
<%= form_with(model: weapon, class: "contents") do |form| %>
  <% if weapon.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(weapon.errors.count, "error") %> prohibited this weapon from being saved:</h2>

      <ul>
        <% weapon.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cost_cp %>
    <%= form.number_field :cost_cp, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :weight %>
    <%= form.text_field :weight, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :damage_dice %>
    <%= form.text_field :damage_dice, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :damage_type_id %>
    <%= form.text_field :damage_type_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/weapons/_weapon.html.erb
<div id="<%= dom_id weapon %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= weapon.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cost cp:</strong>
    <%= weapon.cost_cp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Weight:</strong>
    <%= weapon.weight %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Damage dice:</strong>
    <%= weapon.damage_dice %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Damage type:</strong>
    <%= weapon.damage_type_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this weapon", weapon, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this weapon', edit_weapon_path(weapon), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/weapons/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing weapon</h1>

  <%= render "form", weapon: @weapon %>

  <%= link_to "Show this weapon", @weapon, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to weapons", weapons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/weapons/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Weapons</h1>
    <%= link_to 'New weapon', new_weapon_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="weapons" class="min-w-full">
    <%= render @weapons %>
  </div>
</div>

app/views/weapons/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New weapon</h1>

  <%= render "form", weapon: @weapon %>

  <%= link_to 'Back to weapons', weapons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/weapons/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @weapon %>

    <%= link_to 'Edit this weapon', edit_weapon_path(@weapon), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this weapon', weapon_path(@weapon), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to weapons', weapons_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>