config/routes.rb
Rails.application.routes.draw do
  resources :weapons
  resources :armor_shields
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :features
  resources :languages
  resources :races
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.ransackable_attributes(auth_object = nil)
    self.column_names
  end
end

app/models/armor_shield.rb
class ArmorShield < ApplicationRecord
  enum ac_modifier: [
    :strength,
    :constitution,
    :dexterity,
    :intelligence,
    :wisdom,
    :charisma
  ], _instance_methods: false

  enum category: [
    :light,
    :medium,
    :heavy,
    :shield
  ], _instance_methods: false

  UNITS = [
    :action,
    :bonus_action,
    :reaction,
    :minute,
    :hour,
    :day
  ].freeze

  enum don_unit: UNITS, _instance_methods: false
  enum doff_unit: UNITS, _instance_methods: false
end

app/models/creature_type.rb
class CreatureType < ApplicationRecord
end

app/models/damage_type.rb
class DamageType < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
  has_many :feature_owners, dependent: :destroy, inverse_of: :feature
  has_many :owners, through: :feature_owners
end

app/models/feature_owner.rb
class FeatureOwner < ApplicationRecord
  belongs_to :feature, inverse_of: :feature_owners
  belongs_to :owner, polymorphic: true
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :language_speakers, dependent: :destroy, inverse_of: :language
end

app/models/language_speaker.rb
class LanguageSpeaker < ApplicationRecord
  belongs_to :language, inverse_of: :language_speakers
  belongs_to :speaker, polymorphic: true
end

app/models/race.rb
class Race < ApplicationRecord
  enum size: [:tiny, :small, :medium, :large, :huge, :gargantuan]

  has_many :language_speakers, as: :speaker, dependent: :destroy, inverse_of: :speaker
  has_many :languages, through: :language_speakers
  has_many :features, as: :owner, dependent: :destroy

  validates_presence_of :name, :description
end

app/models/weapon.rb
class Weapon < ApplicationRecord
  belongs_to :damage_type, optional: true
  has_many :weapon_property_weapon, dependent: :destroy
  has_many :weapon_properties, through: :weapon_property_weapon

  enum weapon_type: [
    :simple_melee,
    :simple_ranged,
    :martial_melee,
    :martial_ranged,
    :ammunition,
  ]

  def cost=(cost)
    self.cost_cp = cost_conversion(cost)
  end

  def cost
    # It defaults to gold pieces, since it's standard

    "#{self.cost_cp.to_f / 100} gp"
  end

  def self.ransackable_associations(auth_object = nil)
    ["damage_type", "weapon_properties", "weapon_property_weapon"]
  end

  private

  COST_MAP = {
    'cp' => 1,
    'sp' => 10,
    'ep' => 50,
    'gp' => 100,
    'pp' => 1000,
  }

  def cost_conversion(cost)
    amount, unit = cost.split(' ')

    amount.to_i * COST_MAP[unit]
  end
end

app/models/weapon_property.rb
class WeaponProperty < ApplicationRecord
  has_many :weapon_property_weapon
  has_many :weapons, through: :weapon_property_weapon
end

app/models/weapon_property_weapon.rb
class WeaponPropertyWeapon < ApplicationRecord
  belongs_to :weapon
  belongs_to :weapon_property
end

app/controllers/armor_shields_controller.rb
class ArmorShieldsController < InheritedResources::Base

  private

    def armor_shield_params
      params.require(:armor_shield).permit(:name, :base_ac, :ac_modifier, :cap_ac_modifier, :strength, :stealth_disadvantage, :weight, :cost_cp, :don_unit, :don_amount, :doff_unit, :doff_amount, :category)
    end

end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  before_action :set_feature, only: %i[ show edit update destroy ]

  # GET /features or /features.json
  def index
    @features = Feature.all
  end

  # GET /features/1 or /features/1.json
  def show
  end

  # GET /features/new
  def new
    @feature = Feature.new
  end

  # GET /features/1/edit
  def edit
  end

  # POST /features or /features.json
  def create
    @feature = Feature.new(feature_params)

    respond_to do |format|
      if @feature.save
        format.html { redirect_to feature_url(@feature), notice: "Feature was successfully created." }
        format.json { render :show, status: :created, location: @feature }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /features/1 or /features/1.json
  def update
    respond_to do |format|
      if @feature.update(feature_params)
        format.html { redirect_to feature_url(@feature), notice: "Feature was successfully updated." }
        format.json { render :show, status: :ok, location: @feature }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @feature.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /features/1 or /features/1.json
  def destroy
    @feature.destroy

    respond_to do |format|
      format.html { redirect_to features_url, notice: "Feature was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feature
      @feature = Feature.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feature_params
      params.require(:feature).permit(:name, :description)
    end
end

app/controllers/races_controller.rb
class RacesController < ApplicationController
  before_action :set_race, only: %i[ show edit update destroy ]

  def index
    @races = Race.all
  end

  def show
  end

  def new
    @race = Race.new
  end

  def edit
  end

  def create
    @race = Race.new(race_params)

    respond_to do |format|
      if @race.save
        format.html { redirect_to race_url(@race), notice: "Race was successfully created." }
        format.json { render :show, status: :created, location: @race }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @race.update(race_params)
        format.html { redirect_to race_url(@race), notice: "Race was successfully updated." }
        format.json { render :show, status: :ok, location: @race }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @race.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @race.destroy

    respond_to do |format|
      format.html { redirect_to races_url, notice: "Race was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  def set_race
    @race = Race.find(params[:id])
  end

  def race_params
    params.require(:race).permit(:name, :description, :size, :speed)
  end
end

app/controllers/weapons_controller.rb
class WeaponsController < InheritedResources::Base

  private

    def weapon_params
      params.require(:weapon).permit(:name, :cost_cp, :weight, :damage_dice, :damage_type_id)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/armor_shields_helper.rb
module ArmorShieldsHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/races_helper.rb
module RacesHelper
end

app/helpers/weapons_helper.rb
module WeaponsHelper
end

app/views/armor_shields/_armor_shield.html.erb
<div id="<%= dom_id armor_shield %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= armor_shield.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Base ac:</strong>
    <%= armor_shield.base_ac %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Ac modifier:</strong>
    <%= armor_shield.ac_modifier %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cap ac modifier:</strong>
    <%= armor_shield.cap_ac_modifier %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Strength:</strong>
    <%= armor_shield.strength %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Stealth disadvantage:</strong>
    <%= armor_shield.stealth_disadvantage %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Weight:</strong>
    <%= armor_shield.weight %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Cost cp:</strong>
    <%= armor_shield.cost_cp %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Don unit:</strong>
    <%= armor_shield.don_unit %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Don amount:</strong>
    <%= armor_shield.don_amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Doff unit:</strong>
    <%= armor_shield.doff_unit %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Doff amount:</strong>
    <%= armor_shield.doff_amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Category:</strong>
    <%= armor_shield.category %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this armor shield", armor_shield, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this armor shield', edit_armor_shield_path(armor_shield), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/armor_shields/_form.html.erb
<%= form_with(model: armor_shield, class: "contents") do |form| %>
  <% if armor_shield.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(armor_shield.errors.count, "error") %> prohibited this armor_shield from being saved:</h2>

      <ul>
        <% armor_shield.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :base_ac %>
    <%= form.number_field :base_ac, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :ac_modifier %>
    <%= form.number_field :ac_modifier, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cap_ac_modifier %>
    <%= form.number_field :cap_ac_modifier, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :strength %>
    <%= form.number_field :strength, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :stealth_disadvantage %>
    <%= form.check_box :stealth_disadvantage, class: "block mt-2 h-5 w-5" %>
  </div>

  <div class="my-5">
    <%= form.label :weight %>
    <%= form.number_field :weight, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :cost_cp %>
    <%= form.number_field :cost_cp, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :don_unit %>
    <%= form.number_field :don_unit, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :don_amount %>
    <%= form.number_field :don_amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :doff_unit %>
    <%= form.number_field :doff_unit, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :doff_amount %>
    <%= form.number_field :doff_amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :category %>
    <%= form.number_field :category, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/armor_shields/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing armor shield</h1>

  <%= render "form", armor_shield: @armor_shield %>

  <%= link_to "Show this armor shield", @armor_shield, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to armor shields", armor_shields_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/armor_shields/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Armor shields</h1>
    <%= link_to 'New armor shield', new_armor_shield_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="armor_shields" class="min-w-full">
    <%= render @armor_shields %>
  </div>
</div>

app/views/armor_shields/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New armor shield</h1>

  <%= render "form", armor_shield: @armor_shield %>

  <%= link_to 'Back to armor shields', armor_shields_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/armor_shields/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @armor_shield %>

    <%= link_to 'Edit this armor_shield', edit_armor_shield_path(@armor_shield), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this armor_shield', armor_shield_path(@armor_shield), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to 01_armor_shields.rb', armor_shields_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>